version: '3'

services:
  proxy:
    image: mminks/haproxy-docker-logging
    env_file:
      - .env
    volumes:
      - ${PWD}/haproxy:/usr/local/etc/haproxy:ro
  reverseproxy:
    image: nginx:1.12 # reverseproxy
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/certs:/etc/nginx/ssl:ro
    restart: always
  app:
    image: mendhak/http-https-echo
  api:
    image: mendhak/http-https-echo
  service-app:
    container_name: service-app
    build:
      context: ./service-app/
    volumes:
      - ./service-app:/app/src
  api-service:
    container_name: api-service
    build:
      context: ./api-service/
    volumes:
      - ./api-service:/app/src
